# try {} catch
# --
try {
    $1
} catch (${2:Exception e}) {
    e.printStackTrace();$0
}
